C4Context
title System Diagrama de contexto sistema biopatternsg

Boundary(biopatternsg, "Biopatternsg") {
    System("bioPatternsg","Biopatternsg")
}
Person("user","User")

Boundary(externalServices,"External Services"){
    Boundary(ncbi, "ncbi") {
        System_Ext("mesh","MESH")
        System_Ext("pubtator","PubTator")
        System_Ext("pubmed","PubMed")
    }
    
    System_Ext("pdb","PDB","Busqueda de complejos proteinicos")
    System_Ext("hgnc","HGNC")
    System_Ext("quickgo","QuickGO")
    System_Ext("uniprot","UniProt")
    System_Ext("tfbind","TFbind")
    System_Ext("jasper","Jasper")
    
}

Rel(user,bioPatternsg, "uses")
Rel(bioPatternsg,mesh, "Uses", "Json/Https")
Rel(bioPatternsg,pubtator,"Uses", "Json/Https")
Rel(bioPatternsg,pubmed,"Uses", "Json/Https")
Rel(bioPatternsg,pdb,"Uses", "Json/Https")
Rel(bioPatternsg,hgnc,"Uses", "Json/Https")
Rel(bioPatternsg,quickgo,"Uses", "Json/Https")
Rel(bioPatternsg,uniprot,"Uses", "Json/Https")
Rel(bioPatternsg,tfbind,"Uses", "Html/Https")
Rel(bioPatternsg,jasper,"Uses", "Json/Https")

UpdateLayoutConfig($c4ShapeInRow="4", $c4BoundaryInRow="1")






