C4Component
title gateway container

Boundary(biopatternsg,"Biopatternsg"){

Container_Boundary(gateway,"Gateaway"){

    Component(security,"Security")
    Component(router,"Router")
    Rel(security,router,"uses")
    
}

    Container(control_access,"ControlAccess")
    Container(config_and_control,"ConfigAndControl")
    Container(biological_objects,"BiologicalObjects")
    Container(ontologies,"Obtologies")
    Container(webapp,"Web App")
    Container(rrg_building,"RRGBuilding")

    Rel(webapp,security,"Json/Https")
    Rel(router,control_access, "Json/Https")
    Rel(router,config_and_control, "Json/Https")
    Rel(router,biological_objects, "Json/Https")
    Rel(router,ontologies, "Json/Https")
    Rel(router,rrg_building, "Json/Https")
}


