sequenceDiagram
    participant User
    participant UI
    participant Config-and-control
    participant Keycloak
    participant EmailService as Email

    User->>UI: Enters email address in the UI view
    UI->>Config-and-control: Sends password recovery information via REST API
    Config-and-control->>Keycloak: Sends password recovery information
    Keycloak->>EmailService: Sends email with password reset link
    EmailService->>Keycloak: Redirects to password reset view
    Keycloak->>User: Displays password reset form
    User->>Keycloak: Enters new password
    Keycloak->>UI: Redirects to login view
